poppopjmp/spiderfoot

modules/sfp_zoomeye.py
test/integration/modules/test_sfp_zoomeye.py

Add a new module to interact with the ZoomEye API.
* **New Module (`modules/sfp_zoomeye.py`)**
- Create a new module `sfp_zoomeye.py` to interact with the ZoomEye API.
- Define the class `sfp_zoomeye` inheriting from `SpiderFootPlugin`.
- Implement the `setup`, `watchedEvents`, `producedEvents`, `query`, and `handleEvent` methods.
- Add options for API key, delay, and maximum pages.
- Add logic to query the ZoomEye API and process the results.
* **Tests (`test/integration/modules/test_sfp_zoomeye.py`)**
- Create a new test file `test_sfp_zoomeye.py` for the `sfp_zoomeye` module.
- Write tests for the `setup`, `watchedEvents`, `producedEvents`, `query`, and `handleEvent` methods.
- Mock the ZoomEye API responses for testing.
- Ensure the tests cover various scenarios and edge cases.
--- …

Add ZoomEye API interaction module

---

modules/sfp_rocketreach.py
test/integration/modules/test_sfp_rocketreach.py

Implement RocketReach API interaction in SpiderFoot.
* **New Module**: Add `modules/sfp_rocketreach.py` to interact with the RocketReach API.
- Implement the `sfp_rocketreach` class.
- Include API key handling, query functions, and event handling.
- Handle events such as `EMAILADDR`, `PHONE_NUMBER`, and `SOCIAL_MEDIA`.
- Produce events such as `EMAILADDR`, `PHONE_NUMBER`, `SOCIAL_MEDIA`, and `RAW_RIR_DATA`.
* **Integration Tests**: Add `test/integration/modules/test_sfp_rocketreach.py` for the `sfp_rocketreach` module.
- Test API key handling, query functions, and event handling.
- Verify events such as `EMAILADDR`, `PHONE_NUMBER`, and `SOCIAL_MEDIA` are handled correctly.
- Ensure events such as `EMAILADDR`, `PHONE_NUMBER`, `SOCIAL_MEDIA`, and `RAW_RIR_DATA` are produced correctly.

Add RocketReach API interaction

---

README.md
setup.cfg
spiderfoot/db.py

Add support for PostgreSQL database in `spiderfoot/db.py`.
* Import `psycopg2` and `psycopg2.extras` for PostgreSQL support.
* Add a configuration option to switch between SQLite and PostgreSQL.
* Implement PostgreSQL-specific connection handling and queries.
* Update existing functions to handle both SQLite and PostgreSQL.
* Modify error handling to include `psycopg2.Error` for PostgreSQL.
* Update database initialization to create schema and insert event details for PostgreSQL.
* Add PostgreSQL-specific SQL queries and connection handling.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/poppopjmp/spiderfoot/pull/8?shareId=54bba4e2-02c6-4a00-bc11-c3e9623035b4).

Add PostgreSQL support to SpiderFoot

---

modules/sfp_intelx.py
modules/sfp_tool_trufflehog.py

Potential fix for [https://github.com/poppopjmp/spiderfoot/security/code-scanning/5](https://github.com/poppopjmp/spiderfoot/security/code-scanning/5)
To fix the problem, we need to parse the URL and check the host value to ensure it matches the allowed host correctly. This can be done using the `urlparse` function from the `urllib.parse` module. We will extract the hostname from the URL and then check if it matches the allowed host.
1. Import the `urlparse` function from the `urllib.parse` module.
2. Parse the URL using `urlparse` to extract the hostname.
3. Check if the hostname matches the allowed host (`public.intelx.io`).
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 5: Incomplete URL substring sanitization

---

modules/sfp_abstractapi.py
modules/sfp_webserver.py
modules/sfp_wikileaks.py

Potential fix for [https://github.com/poppopjmp/spiderfoot/security/code-scanning/1](https://github.com/poppopjmp/spiderfoot/security/code-scanning/1)
To fix the problem, we need to parse the URL and check its hostname to ensure it matches the expected domain. This can be done using the `urlparse` function from the `urllib.parse` module. Specifically, we should extract the hostname from the URL and verify that it ends with `linkedin.com`.
- Parse the URL using `urlparse`.
- Extract the hostname from the parsed URL.
- Check if the hostname ends with `linkedin.com`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 1: Incomplete URL substring sanitization

---

correlations/README.md
correlations/fofa_exposed_services.yaml
correlations/internal_service_exposed.yaml
correlations/rocketreach_exposed_contacts.yaml
correlations/zoomeye_exposed_services.yaml
modules/sfp_rocketreach.py

Add a new correlation rule to detect internal services exposed to the internet.
* **New Rule**: Add `correlations/internal_service_exposed.yaml` to detect internal services exposed to the internet using common internal service ports (8080, 8443).
* **Documentation**: Update `correlations/README.md` to include an example of the new correlation rule.

Add internal service exposed rule

---

modules/sfp__stor_db.py
modules/sfp__stor_elasticsearch.py
modules/sfp__stor_stdout.py
requirements.txt
sf.py
test/integration/modules/test_sfp__stor_elasticsearch.py

Add functionality to feed scan data to ElasticSearch.
* **New Module**: Add `modules/sfp__stor_elasticsearch.py` to store scan results in an ElasticSearch cluster.
- Implement `setup` method to initialize the module and configure ElasticSearch connection settings.
- Implement `watchedEvents` method to define the events of interest.
- Implement `handleEvent` method to send data to ElasticSearch.
* **Main Script**: Modify `sf.py` to include the new module in the list of available modules.
- Update the `start_scan` function to add `sfp__stor_elasticsearch` to the `modlist`.
* **Tests**: Add `test/integration/modules/test_sfp__stor_elasticsearch.py` to test the new ElasticSearch module.
- Test the `setup` method to ensure proper initialization.
- Test the `watchedEvents` method to ensure …

Add ElasticSearch storage module

---

.github/workflows/docker-image.yml
Pipfile
Pipfile.lock
README.md
modules/sfp_netlas.py
requirements.txt
test/integration/modules/test_sfp_netlas.py
test/unit/modules/test_sfp_netlas.py

Add Netlas API integration and update version to 5.0.2.
* **New Module**: Add `sfp_netlas.py` to implement Netlas API integration.
- Implement `setup`, `watchedEvents`, `producedEvents`, `queryNetlas`, `parseApiResponse`, and `handleEvent` methods.
- Define `meta` dictionary with module information.
* **README Update**: Update version to 5.0.2 and add Netlas module to the list of available modules.
* **Dependencies**: Add Netlas dependency to `Pipfile`, `Pipfile.lock`, and `requirements.txt`.
* **Tests**: Add integration and unit tests for the Netlas module in `test/integration/modules/test_sfp_netlas.py` and `test/unit/modules/test_sfp_netlas.py`.

Add netlas API integration and update version to 5.0.2

---

sf.py
spiderfoot/api.py

Add REST API implementation using FastAPI.
* **Add `spiderfoot/api.py`**:
- Create a new FastAPI application instance named `app`.
- Define a simple root endpoint for testing with the path `/`.
- Import necessary modules and dependencies, including `FastAPI`.
* **Modify `sf.py`**:
- Import the `app` instance from `spiderfoot/api`.
- Update the `start_rest_api_server` function to start the FastAPI server using Uvicorn.
- Ensure the `--rest-api` command-line argument starts the REST API server by calling `start_rest_api_server`.

Implement REST API for SpiderFoot

---

requirements.txt
sf.py
sfwebui.py
spiderfoot/api.py
spiderfoot/static/js/spiderfoot.js

Implement a REST API for communication with Python core modules and update the frontend to use the new name "mirage" in Node.js.
* **sf.py**
- Add a new argument `--rest-api` to start the REST API server using FastAPI.
- Add a function `start_rest_api_server` to start the REST API server using FastAPI and Uvicorn.
* **sfwebui.py**
- Remove references to CherryPy and its configurations.
* **requirements.txt**
- Add `fastapi` and `uvicorn` to the requirements.
* **spiderfoot/static/js/spiderfoot.js**
- Update API endpoints to use `/api` prefix for search, scan delete, and stop scan functions.

Implement REST API for communication with Python core modules

---

spiderfoot/static/package.json
spiderfoot/static/webpack.config.js

Add a build script and Webpack configuration for the Node.js web interface.
* Modify `spiderfoot/static/package.json` to include a `build` script and add `webpack` and `webpack-cli` as devDependencies.
* Add `spiderfoot/static/webpack.config.js` to configure Webpack for bundling the React components.
* Set the entry point to `./js/index.js` and the output path to `./dist` with the filename `bundle.js`.
* Add rules to handle JavaScript and JSX files using `babel-loader`.

Add build script for Node.js web interface

---

README.md
react-web-interface/README.md
react-web-interface/package.json
react-web-interface/server.js
react-web-interface/src/App.js
react-web-interface/src/emotionalDesign.js
react-web-interface/src/spiderfootFunctions.js
sfwebui.py
spiderfoot/api.py

Expand the REST API implementation to include all Spiderfoot functionalities and update the documentation.
* **API Endpoints**:
- Add endpoints for starting scans, stopping scans, retrieving scan results, listing available modules, listing active scans, getting scan status, listing scan history, exporting scan results, importing API keys, and exporting API keys in `spiderfoot/api.py`.
- Implement logic for each new endpoint to interact with Spiderfoot's core functionalities.
- Add error handling and validation for the new endpoints.
* **Documentation**:
- Update `README.md` to include a new section for REST API usage with detailed instructions and examples.
- Add instructions for running the REST API server.
- List available endpoints and provide example usage for each.

Add REST API implementation for Spiderfoot functionalities

---

react-web-interface/README.md
react-web-interface/client/package.json
react-web-interface/client/src/App.js
react-web-interface/client/src/index.js
react-web-interface/package.json
react-web-interface/server.js

Add client functionality to the SpiderFoot React Web Interface.
* **Server Changes:**
- Modify `react-web-interface/server.js` to serve static files from the `client/build` directory.
- Update the root route to serve `index.html` from the `client/build` directory.
* **Package Configuration:**
- Add a build script to `react-web-interface/package.json` to build the React app.
- Update the `start` script to serve the built React app.
* **Documentation:**
- Update `react-web-interface/README.md` with instructions for building and serving the production version of the React app.
* **Client Setup:**
- Add `react-web-interface/client/package.json` with necessary dependencies and scripts.
- Add `react-web-interface/client/src/index.js` to render the React app.
- Add …

Add client functionality to React web server

---

test/integration/modules/test_sfp__stor_elasticsearch.py
test/integration/modules/test_sfp_abusech.py
test/integration/modules/test_sfp_abuseipdb.py
test/integration/test_sfwebui.py

Add timeouts and retries to network requests and Elasticsearch setup in integration tests to prevent pytest from hanging.
* **test/integration/modules/test_sfp_abusech.py**
- Add a timeout parameter to the `requests.get` call in the `test_handleEvent_malicious_ip`, `test_handleEvent_benign_ip`, and `test_handleEvent_api_error` tests.
- Add retries with exponential backoff to the `requests.get` call in the `test_handleEvent_malicious_ip` and `test_handleEvent_benign_ip` tests.
* **test/integration/modules/test_sfp_abuseipdb.py**
- Add a timeout parameter to the `requests.get` call in the `test_handleEvent_malicious_ip` test.
- Add retries with exponential backoff to the `requests.get` call in the `test_handleEvent_malicious_ip` test.
* …

Fix pytest hang during integration tests

---

Dockerfile

Update `Dockerfile` to address various Dockerfile best practices and warnings.
* Pin versions in `apt-get install` commands to specific versions.
* Delete the apt-get lists after installing packages.
* Specify `--no-install-recommends` in `apt-get install` commands.
* Consolidate multiple consecutive `RUN` instructions.
* Use `pip install --no-cache-dir` for pip installations.
* Pin versions in `pip install` commands to specific versions.
* Set `WORKDIR` before `COPY` instructions.
* Use `cd ... || exit` in case `cd` fails.

Fix Dockerfile issues and warnings

---

spiderfoot/api.py

Fix invalid syntax in return statement in `spiderfoot/api.py`.
* Add an underscore between `active` and `scans` in the return statement at line 73.
* Ensure the return statement is `return {"active_scans": active_scans}`.

Fix syntax error in return statement

---

requirements.txt
spiderfoot/api.py

Update `spiderfoot/api.py` to fix undefined names and improve exception handling.
* **Imports:**
- Import `List` from `typing`.
- Import `SpiderFootTarget` from `spiderfoot`.
- Import `logging` module.
* **Exception Handling:**
- Update all `raise HTTPException` statements to use `raise ... from err`.
- Replace generic `Exception` with more specific exception types (`ValueError`, `TypeError`) where appropriate.
- Add logging for exceptions before raising `HTTPException`.
* **requirements.txt:**
- Add `logging` module to the requirements.

Fix exception handling in spiderfoot/api.py

---

react-web-interface/client/package.json
react-web-interface/package.json

Add `package-lock.json` entries to `package.json` files.
* **react-web-interface/client/package.json**
- Add `"package-lock.json": {}` entry.
* **react-web-interface/package.json**
- Add `"package-lock.json": {}` entry.

Fix Dockerfile to include package-lock.json

---

react-web-interface/Dockerfile
react-web-interface/client/package.json
react-web-interface/package.json

Update the npm build process for the React web interface to complete successfully without errors.
* **Dockerfile Changes**
- Add `RUN npm install react-scripts` before `RUN npm run build` to ensure `react-scripts` is installed.
* **Package.json Changes**
- Update `react-web-interface/package.json` to include `react-scripts` dependency with version `^5.0.1`.
- Update `react-web-interface/client/package.json` to include `react-scripts` dependency with version `^5.0.1`.

Fix react-scripts not found error in Dockerfile

---

react-web-interface/Dockerfile
react-web-interface/client/package.json

Update `react-web-interface/client/package.json` and `react-web-interface/Dockerfile` to fix npm build script errors.
* **`react-web-interface/client/package.json`**:
- Add `react-scripts` to `devDependencies`.
- Remove `react-scripts` from `dependencies`.
* **`react-web-interface/Dockerfile`**:
- Remove `RUN npm install react-scripts`.
- Add `RUN npm install --only=dev` before `RUN npm run build`.

Fix npm build script for react-web-interface

---

README.md
correlations/README.md
modules/sfp_leakcheck.py
modules/sfp_whoisfreaks.py
test/integration/modules/test_sfp_whoisfreaks.py

Add `sfp_leakcheck` plugin to gather breach data from LeakCheck API.
* **New Methods**:
- Add `query` method to handle API requests to LeakCheck.
- Add `handleEvent` method to process events and generate specified events.
* **Event Handling**:
- Update `watchedEvents` method to include `EMAILADDR`, `DOMAIN_NAME`, and `PHONE_NUMBER`.
- Update `producedEvents` method to include `EMAILADDR_COMPROMISED`, `ACCOUNT_EXTERNAL_OWNED_COMPROMISED`, `PHONE_NUMBER_COMPROMISED`, and more.
* **Setup**:
- Update `setup` method to initialize the plugin with user options.
* **Error Handling**:
- Add error handling for invalid API credentials, missing API key, and too many requests.
* **Event Notification**:
- Notify listeners for various events such as `EMAILADDR_COMPROMISED`, …

Add LeakCheck plugin to gather breach data

---

README.md
correlations/README.md
modules/sfp_deepinfo.py
modules/sfp_leakcheck.py
modules/sfp_whoisfreaks.py
test/integration/modules/test_sfp_whoisfreaks.py

Add functionality to query Deepinfo API for Passive DNS information.
* Add a new method `query_passive_dns` to query the Deepinfo API for Passive DNS information.
* Update the `producedEvents` method to include `INTERNET_NAME` and `INTERNET_NAME_UNRESOLVED`.
* Update the `handleEvent` method to handle `INTERNET_NAME` events and query the Deepinfo API for Passive DNS information.
* Update the `query` method to handle both subdomain and Passive DNS queries.

Add Passive DNS query to sfp_deepinfo plugin

---

.github/workflows/docker-image.yml
react-web-interface/Dockerfile
react-web-interface/client/package.json
react-web-interface/package.json

Add container build of the React web app to the container CI.
* **New Job `build-react-web-app`**:
- Add a new job `build-react-web-app` to build the React web app container.
- Use `docker/setup-buildx-action@v3` to set up Docker Buildx.
- Use `hadolint/hadolint-action@v3.1.0` to lint the `react-web-interface/Dockerfile`.
- Use `docker/login-action@v3` to log in to GitHub Container Registry.
- Use `docker/build-push-action@v5` to build and push the React web app Docker image.
- Add a step to run container tests for the React web app.

Add React web app container CI

---

test/integration/modules/test_sfp__stor_db.py
test/integration/modules/test_sfp__stor_elasticsearch.py
test/integration/modules/test_sfp__stor_stdout.py
test/integration/modules/test_sfp_abstractapi.py
test/integration/modules/test_sfp_abusech.py
test/integration/modules/test_sfp_abuseipdb.py
test/integration/modules/test_sfp_abusix.py

Refactor test files to eliminate redundancy and improve test structure.
* **Base Test Class**: Introduce `BaseTestModuleIntegration` class to handle common setup and event creation logic.
* **test_sfp__stor_db.py**: Refactor to use `BaseTestModuleIntegration` for shared test structures.
* **test_sfp__stor_stdout.py**: Refactor to use `BaseTestModuleIntegration` for shared test structures.
* **test_sfp_abusech.py**: Refactor to use `BaseTestModuleIntegration` for shared mock API response tests.
* **test_sfp_abuseipdb.py**: Refactor to use `BaseTestModuleIntegration` for shared mock API response tests.
* **test_sfp_abusix.py**: Refactor to use `BaseTestModuleIntegration` for shared mock API response tests.
* **test_sfp__stor_elasticsearch.py**: Refactor to use `BaseTestModuleIntegration` …

Refactor tests to eliminate redundancy

---

.github/workflows/docker-image.yml
react-web-interface/server.js
spiderfoot/api.py

Add handling for OPTIONS requests to resolve 404 errors for various endpoints.
* **react-web-interface/server.js**
- Add a route to handle OPTIONS requests for `/api/start_scan` and respond with appropriate headers.
- Add a route to handle OPTIONS requests for `/api/active_scans` and respond with appropriate headers.
- Add a route to handle OPTIONS requests for `/api/modules` and respond with appropriate headers.
- Add a route to handle OPTIONS requests for `/api/configure_module` and respond with appropriate headers.
- Add a route to handle OPTIONS requests for `/api/export_scan_results` and respond with appropriate headers.
* **spiderfoot/api.py**
- Add a route to handle OPTIONS requests for `/start_scan` and respond with appropriate headers.
- Add a route to handle OPTIONS requests for …

Fix API endpoints to handle OPTIONS requests

---

sfapi.py

Import the SpiderFoot class from sflib.py and the SpiderFootDb class from spiderfoot/db.py in sfapi.py.
Initialize the SpiderFoot class with the configuration options and set up logging using the logListenerSetup and logWorkerSetup functions.
* Import the SpiderFoot class from sflib.py.
* Import the SpiderFootDb class from spiderfoot/db.py.
* Import the logListenerSetup and logWorkerSetup functions from spiderfoot/logger.py.
* Initialize the SpiderFoot class with the configuration options.
* Set up logging using the logListenerSetup and logWorkerSetup functions.

Initialize SpiderFoot class with configuration options and set up logging

---

modules/sfp_comodo.py
sf.py
sfapi.py
spiderfoot/__init__.py

Remove redundant and duplicate code, and clean up unused imports and comments.
* **sf.py**:
- Remove redundant code for setting up the web server and REST API server.
- Remove unused imports.
- Remove redundant comments and debug statements.
- Remove duplicate `import uvicorn` statement.
* **sfapi.py**:
- Consolidate HTTP options request handling.
- Remove unused imports.
- Remove redundant comments and debug statements.
* **spiderfoot/__init__.py**:
- Remove redundant `__version__` variable.
* **modules/sfp_comodo.py**:
- Remove leftover comment block.

Remove redundant code and clean up

---

modules/sfp_abstractapi.py
modules/sfp_azureblobstorage.py
modules/sfp_digitaloceanspace.py
modules/sfp_googleobjectstorage.py
modules/sfp_s3bucket.py

Potential fix for [https://github.com/poppopjmp/spiderfoot/security/code-scanning/18](https://github.com/poppopjmp/spiderfoot/security/code-scanning/18)
To fix the problem, we need to parse the URL and check the hostname to ensure it belongs to "linkedin.com". This can be done using the `urlparse` function from the `urllib.parse` module. We will extract the hostname and verify that it ends with "linkedin.com".
- Parse the URL using `urlparse`.
- Extract the hostname from the parsed URL.
- Check if the hostname ends with "linkedin.com".
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 18: Incomplete URL substring sanitization

---

modules/sfp_tool_cmseek.py

Hi,
First of all, thank you for taking over this project, as I think it has a lot of potential.
I wrote a fix at the time because the CMSeeK plugin wasn't returning all the info.  For example, we were missing the Wordpress version, its plugins and its users. I'd started to select the fields, but I think it's better to return the whole json to get all the info, whatever the CMS.
I've also fix a problem with the scan result path, which seems to have changed since the fork. By default, CMSeeK seems to save its scan in the current folder, and there's no option to configure this. It seems that your fork uses the spiderfoot home, so I've added a condition to the code.

CMSeeK fix “Result” folder and send full json
